# Generated by Django 2.0.3 on 2018-05-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_team', models.CharField(max_length=50)),
                ('left_rarity', models.CharField(max_length=50)),
                ('right_team', models.CharField(max_length=50)),
                ('right_rarity', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
