# Generated by Django 2.0.3 on 2018-04-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0002_djangomigrations_eventbosstreasurebox_eventbosstreasurecontent_eventenemyparameter_eventenemyrewardg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatsuneQuestRewardDataCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('equipment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcrd_unpack.EquipmentData')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcrd_unpack.ItemData')),
                ('quest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pcrd_unpack.HatsuneQuest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
