# Generated by Django 2.0.3 on 2018-04-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0004_pcrdunpackhatsunequestrewarddatacustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSummary',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pcrd_unpack.UnitData')),
                ('hp', models.FloatField(default=0)),
                ('hp_recovery_rate', models.FloatField(default=0)),
                ('wave_hp_recovery', models.FloatField(default=0)),
                ('energy_recovery_rate', models.FloatField(default=0)),
                ('wave_energy_recovery', models.FloatField(default=0)),
                ('atk', models.FloatField(default=0)),
                ('magic_str', models.FloatField(default=0)),
                ('def_field', models.FloatField(default=0)),
                ('magic_def', models.FloatField(default=0)),
                ('physical_critical', models.FloatField(default=0)),
                ('magic_critical', models.FloatField(default=0)),
                ('dodge', models.FloatField(default=0)),
                ('life_steal', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
