# Generated by Django 2.0.3 on 2018-05-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0005_remove_teams_team_id'),
    ]
    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
