# Generated by Django 2.0.3 on 2018-05-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0006_auto_20180529_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='left_team',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='right_team',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
