# Generated by Django 2.0.3 on 2018-05-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0007_auto_20180529_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_team', to='pcrd_unpack.Team')),
                ('right_team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_team', to='pcrd_unpack.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
