# Generated by Django 2.0.3 on 2018-05-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0010_auto_20180530_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionComments',
            new_name='SolutionComment',
        ),
    ]
