# Generated by Django 2.0.3 on 2018-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0011_auto_20180530_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='pub_data',
            field=models.DateField(auto_now=True),
        ),
    ]
