# Generated by Django 2.0.3 on 2018-06-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0013_solutioncomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsummary',
            name='energy_reduce_rate',
            field=models.FloatField(default=0),
        ),
    ]
