# Generated by Django 2.0.3 on 2018-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrd_unpack', '0014_unitsummary_energy_reduce_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharaIdentity',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chara_type', models.IntegerField()),
            ],
            options={
                'db_table': 'chara_identity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventNaviCommentCondition',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('condition_type_1', models.IntegerField()),
                ('condition_value_1', models.IntegerField()),
                ('condition_type_2', models.IntegerField()),
                ('condition_value_2', models.IntegerField()),
                ('condition_type_3', models.IntegerField()),
                ('condition_value_3', models.IntegerField()),
            ],
            options={
                'db_table': 'event_navi_comment_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventTopAdv',
            fields=[
                ('event_top_adv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('value_1', models.IntegerField()),
                ('value_2', models.IntegerField()),
                ('value_3', models.IntegerField()),
                ('story_id', models.IntegerField()),
                ('character_id', models.IntegerField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
            ],
            options={
                'db_table': 'event_top_adv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HatsuneUnlockUnitCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('condition_mission_id', models.IntegerField()),
                ('top_description', models.TextField()),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
            ],
            options={
                'db_table': 'hatsune_unlock_unit_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitMotionList',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sp_motion', models.IntegerField()),
            ],
            options={
                'db_table': 'unit_motion_list',
                'managed': False,
            },
        ),
    ]
